# Generated by Django 2.2.2 on 2019-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vires_oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('admin', 'VirES administration'), ('swarm', 'Access to VirES for Swarm'), ('swarm_vre', 'Access to Swarm VRE'), ('swarm_disc', 'Access to Swarm DISC')],
                'managed': False,
            },
        ),
    ]
