# Generated by Django 3.2.25 on 2024-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vires_oauth', '0002_userprofile_consented_service_terms_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=128, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
