# Generated by Django 2.2.10 on 2020-05-14 15:41
# Data migrations implemented manually.

from hashlib import sha256
from django.db import migrations, models


def hash_tokens(apps, schema_editor):
    model = apps.get_model("eoxs_allauth", "AuthenticationToken")
    for obj in model.objects.all():
        obj.token_sha256 = sha256(obj.token.encode('utf-8')).digest()
        obj.token = None
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eoxs_allauth', '0002_authenticationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationtoken',
            name='token_sha256',
            field=models.BinaryField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authenticationtoken',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(hash_tokens),
    ]
