# Generated by Django 2.2.10 on 2020-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoxs_allauth', '0004_remove_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationtoken',
            name='scopes_packed',
            field=models.CharField(default=' ViresApp ', max_length=128),
            preserve_default=False,
        ),
    ]
