# Generated by Django 3.2.25 on 2026-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoxs_allauth', '0005_authenticationtoken_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationtoken',
            name='purpose',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
