# Generated by Django 2.2.9 on 2020-02-12 18:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-z_][a-zA-Z0-9_]*$'), message='Invalid identifier.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-z_][a-zA-Z0-9_]*$'), message='Invalid identifier.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='vires.ProductType')),
            ],
            options={
                'verbose_name': 'Product Collection',
                'verbose_name_plural': 'Product Collections',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('datasets', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='vires.ProductCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('process_id', models.CharField(max_length=256)),
                ('response_url', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('stopped', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('A', 'ACCEPTED'), ('R', 'STARTED'), ('S', 'SUCCEEDED'), ('T', 'ABORTED'), ('F', 'FAILED'), ('U', 'UNDEFINED')], default='U', max_length=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WPS Job',
                'verbose_name_plural': 'WPS Jobs',
            },
        ),
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=4096)),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=4096)),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
