# Generated by Django 2.2.28 on 2023-04-03 11:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vires', '0002_productlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=64)),
                ('spacecraft', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('mission', 'spacecraft')},
            },
        ),
        migrations.AddField(
            model_name='productcollection',
            name='spacecraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='vires.Spacecraft'),
        ),
        migrations.CreateModel(
            name='CachedMagneticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('expression', models.CharField(max_length=1024)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cached_magnetic_models', to='vires.ProductCollection')),
            ],
            options={
                'unique_together': {('collection', 'expression')},
            },
        ),
    ]
