# Generated by Django 3.2.23 on 2023-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vires', '0004_productcollection_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedmagneticmodel',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clientstate',
            name='state',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='customdataset',
            name='info',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='info',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasets',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='definition',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
